USE [master]
GO

/****** Object:  Database [ITEnvironment]    Script Date: 20.03.2019 14:02:15 ******/
CREATE DATABASE [ITEnvironment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'It_BASE_mdf', FILENAME = N'D:\Учеба\4 сем\курсовой\Environment\data_base\It_BASE.mdf' , SIZE = 5120KB , MAXSIZE = 10240KB , FILEGROWTH = 1024KB ), 
( NAME = N'It_BASE_ndf', FILENAME = N'D:\Учеба\4 сем\курсовой\Environment\data_base\It_BASE.ndf' , SIZE = 5120KB , MAXSIZE = 10240KB , FILEGROWTH = 10%), 
 FILEGROUP [G1] 
( NAME = N'It_BASE11_ndf', FILENAME = N'D:\Учеба\4 сем\курсовой\Environment\data_base\It_BASE11.ndf' , SIZE = 10240KB , MAXSIZE = 15360KB , FILEGROWTH = 1024KB ), 
( NAME = N'It_BASE12_ndf', FILENAME = N'D:\Учеба\4 сем\курсовой\Environment\data_base\It_BASE12.ndf' , SIZE = 2048KB , MAXSIZE = 5120KB , FILEGROWTH = 1024KB ), 
 FILEGROUP [G2] 
( NAME = N'It_BASE21_ndf', FILENAME = N'D:\Учеба\4 сем\курсовой\Environment\data_base\It_BASE21.ndf' , SIZE = 5120KB , MAXSIZE = 10240KB , FILEGROWTH = 1024KB ), 
( NAME = N'It_BASE22_ndf', FILENAME = N'D:\Учеба\4 сем\курсовой\Environment\data_base\It_BASE22.ndf' , SIZE = 2048KB , MAXSIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'It_BASE_log', FILENAME = N'D:\Учеба\4 сем\курсовой\Environment\data_base\It_BASE.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

ALTER DATABASE [ITEnvironment] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ITEnvironment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ITEnvironment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ITEnvironment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ITEnvironment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ITEnvironment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ITEnvironment] SET ARITHABORT OFF 
GO

ALTER DATABASE [ITEnvironment] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ITEnvironment] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ITEnvironment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ITEnvironment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ITEnvironment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ITEnvironment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ITEnvironment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ITEnvironment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ITEnvironment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ITEnvironment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ITEnvironment] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ITEnvironment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ITEnvironment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ITEnvironment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ITEnvironment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ITEnvironment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ITEnvironment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ITEnvironment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ITEnvironment] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ITEnvironment] SET  MULTI_USER 
GO

ALTER DATABASE [ITEnvironment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ITEnvironment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ITEnvironment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ITEnvironment] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ITEnvironment] SET  READ_WRITE 
GO


